name: Packer
on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          packer-version: 1.7.1
          working-directory: packer
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          packer-version: 1.7.1
          working-directory: packer
          command: validate
          arguments: -syntax-only
          target: packer.amzn2.aws.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          packer-version: 1.7.1
          working-directory: packer
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer.amzn2.aws.pkr.hcl
        env:
          PACKER_LOG: 1
