name: Packer
on:
  push: 
    branches:
      - main
  pull_request:

jobs:

  build_id:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set build id'
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +%s)"
      - name: 'Save build id'
        # store the build id to a folder that we can later cache.
        run: |
          mkdir -p .build-id 
          echo $BUILD_ID > .build-id/id
        env:
          BUILD_ID: ${{ steps.build_id.outputs.id }}

  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: PackerSessionName
          
      - name: Identity Check
        run: aws sts get-caller-identity

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: packer
          command: validate
          arguments: -syntax-only
          target: packer.amzn2.aws.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: packer
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer.amzn2.aws.pkr.hcl
        env:
          PACKER_LOG: 1
